---
title: 'Supervised statistical classification-Multinomial'
author: "Suraj Kumar"
date: "15/09/2021"
output: github_document
number_sections: yes
always_allow_html: true

fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#work left, commenting, additing proporation table, start making a ppt

```{r,echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(moderndive)
library(skimr)
library(kableExtra)
library(gridExtra)
library(GGally)
library(infer)
library(broom)
library(ggfortify)
library(jtools)
library(AER)
library(car)
library(janitor)
library(plotly)
library(nnet)
library(rpart)
library(rpart.plot)
library(randomForest)
library(neuralnet)
library(nnet)
library(VGAM)
library(NeuralNetTools)
library(MASS)
```


```{r dataset, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ablone<-read.csv("/home/suraj/Desktop/stats_folder/Supervised/Abalone.txt")
#loaded the dataset
ablone$sex <- as.factor(ablone$sex)
ablone$rings <- as.factor(ablone$rings)

car<-read.csv("/home/suraj/Desktop/stats_folder/Supervised/Car Evaluation.txt")
#loaded the dataset

car[sapply(car,is.character)]<-lapply(car[sapply(car,is.character)],as.factor)
#modified character variable to factor
contra <- read.csv("/home/suraj/Desktop/stats_folder/Supervised/Contraceptive Method Choice.txt")
contra[sapply(contra,is.character)]<-lapply(contra[sapply(contra,is.character)],as.factor)

nursery <- read.csv("/home/suraj/Desktop/stats_folder/Supervised/Nursery.txt")
nursery[sapply(nursery,is.character)]<-lapply(nursery[sapply(nursery,is.character)],as.factor)
```



```{r Exploratory & formal analysis ablone, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
skim(ablone)

tab <- table(ablone$rings)
tab<- as.data.frame(tab)
colnames(tab) <- c("rings", "number")

ggplot(data = tab, mapping = aes(x =rings, y = number)) +
  geom_col()

ablone %>%
  tabyl(rings,sex) %>%
  adorn_percentages() %>%
  adorn_pct_formatting() %>%
  adorn_ns()

rings.sex<- table(ablone$rings,ablone$sex)
 rings.sex <- as.data.frame( rings.sex)
 colnames(rings.sex) <- c("rings", "sex", "number")

 ggplot(data = rings.sex, mapping = aes(x = rings, y = number, fill = sex)) +
  geom_col() +
  labs(x = "rings", y = "frequency",
        title = "rings distribution sex wise") 

ggplot(data = rings.sex, mapping = aes(x = rings, y = number, fill = sex)) +
  geom_col(position = "dodge") +
  labs(x = "rings", y = "sex",
        title = "rings distribution  sex wise") 

ggplot(data = rings.sex, mapping = aes(x = rings, y = number, fill = sex)) +
  geom_col() +
  facet_wrap(~sex,ncol = 1)
  labs(x = "rings", y = "sex",
        title = "rings distribution sex wise") 


ablone %>%
  ggplot(aes(x = rings,y = length),color = sex) +
  geom_boxplot() +
  facet_wrap("sex")
  labs(x = "ablone rings", y = "length",title="Boxplot of ablone length vs rings for different sex")
  
  
ablone %>%
  ggplot(aes(x = rings,y = ablone$diameter),color = sex) +
  geom_boxplot() +
  facet_wrap("sex")
  labs(x = "ablone rings", y = "length",title="Boxplot of ablone length vs rings for different sex")
  
ablone %>%
  ggplot(aes(x = rings,y = ablone$height),color = sex) +
  geom_boxplot() +
  facet_wrap("sex")
  labs(x = "ablone rings", y = "length",title="Boxplot of ablone length vs rings for different sex")
  
ablone %>%
  ggplot(aes(x = rings,y = ablone$whole.weight),color = sex) +
  geom_boxplot() +
  facet_wrap("sex")
  labs(x = "ablone rings", y = "length",title="Boxplot of ablone length vs rings for different sex")
  
ablone %>%
  ggplot(aes(x = rings,y = ablone$shucked.weight),color = sex) +
  geom_boxplot() +
  facet_wrap("sex")
  labs(x = "ablone rings", y = "length",title="Boxplot of ablone length vs rings for different sex")

ablone %>%
  ggplot(aes(x = rings,y = ablone$viscera.weight),color = sex) +
  geom_boxplot() +
  facet_wrap("sex")
  labs(x = "ablone rings", y = "length",title="Boxplot of ablone length vs rings for different sex")
  
ablone %>%
  ggplot(aes(x = rings,y = ablone$shell.weight),color = sex) +
  geom_boxplot() +
  facet_wrap("sex")
  labs(x = "ablone rings", y = "length",title="Boxplot of ablone length vs rings for different sex")
  
 ablone %>%
  select(-c(sex,rings))%>%
  ggpairs()

        


#No missing data

#addresesing outliers
plot<-ablone %>%
  select(-c(sex,rings))%>%
  ggplot(aes(x = length,y = height)) +
  geom_point() 
  
 
sp<-ggplotly(plot)

outliers <- which(ablone$height >=0.500)



ablone.upd<- ablone %>%
  slice(-outliers)


ablone.upd %>%
  select(-c(sex,rings))%>%
  ggpairs()

#high multicolinearity, apply pca
ablone.upd %>%
  select(-c(sex,rings))%>%
  summarise_if(is.numeric,
               list(v= var),na.rm = T)
  
ablone.pca <-ablone.upd %>%
  select(-c(sex,rings))%>% 
  princomp(cor=T)

ablone.pr <-ablone.upd %>%
  select(-c(sex,rings))%>% 
  prcomp(cor=T)

maxs <- apply(ablone.upd[,2:8], 2, max)
mins <- apply(ablone.upd[,2:8], 2, min)

#dividing the data set into training and testing sub datasets
split <- c(0.5,0.55,0.6,0.65,0.7)
n <- dim(ablone.upd)[1]

result.abl<- data.frame(method = c("Simple Multinomial","Reduced Variable Multinomial","PCA Multinomial", "RandomForest","Neural Network"), training.error = c(0),test.error = c(0))

for(alpha in slpit)
{
set.seed(1)
ind <- sample(c(1:n),alpha*n) 
ablone.train <- ablone.upd[ ind,] 
ablone.test <- ablone.upd[-ind,]
#performance checking for simple multinomial

multinom.abl <- multinom( rings ~ .,data = ablone.train,maxit = 1000)

result.abl[1,"test.error"]<-mean(as.character(ablone.test$rings)!=as.character(predict(multinom.abl,ablone.test)))*20

result.abl[1,"training.error"]<-mean(as.character(ablone.train$rings)!=as.character(predict(multinom.abl)))*20

#variable selection
step_both_abl <- stepAIC(multinom.abl, direction="both",trace = FALSE)

result.abl[2,"test.error"]<-mean(as.character(ablone.test$rings)!=as.character(predict(step_both_abl,ablone.test)))*20

result.abl[2,"training.error"]<-mean(as.character(ablone.train$rings)!=as.character(predict(step_both_abl)))*20

#using pca
m2 <- multinom( ablone.train$rings~ablone.pca$scores[ind,1]+ablone.pca$scores[ind,2] + ablone.train$sex,maxit = 1000)


result.abl[3,"training.error"]<-mean(as.character(ablone.train$rings)!=as.character(predict(m2)))*20
df<- data.frame(ablone.pca$scores[-ind,1],ablone.pca$scores[-ind,2] , ablone.test$sex)

result.abl[3,"test.error"]<-mean(as.character(ablone.test$rings)!=as.character(predict(m2,df)))*20

#randomForest
ablone.raf <- randomForest(rings~., data = ablone.train, ntree = 200)
varImpPlot(ablone.raf)
result.abl[4,"training.error"]<-mean(as.character(ablone.train$rings)!=as.character(predict(ablone.raf)))*20
result.abl[4,"test.error"]<-mean(as.character(ablone.test$rings)!=as.character(predict(ablone.raf,ablone.test)))*20

#neural network
ablone.train[,2:8]<-scale(ablone.train[,2:8], center = mins, scale = maxs - mins)
ablone.test[,2:8]<-scale(ablone.test[,2:8], center = mins, scale = maxs - mins)

trainData <- cbind(class.ind(ablone.train$sex),ablone.train[, 2:8], class.ind(ablone.train$rings))


testData <- cbind(class.ind(ablone.test$sex),ablone.test[, 2:8], class.ind(ablone.test$rings))
set.seed(80)

nn_ablone <- neuralnet(  `5`+ `6` + `7` + `8` + `9` + `10` + `11` + `12` + `13` + `14` + `15` + `16` + `17` + `18` + `19` + `20`   ~ F + I + M + length + diameter + height + whole.weight + shucked.weight + viscera.weight + shell.weight,data=trainData,hidden = c(3) ,linear.output=FALSE,err.fct='ce')

original_values <- max.col(trainData[,c(15:30)])
predictions <- max.col(nn_ablone$net.result[[1]])
result.abl[5,"train.error"]<-mean(original_values!=predictions)*20

compute_test <- neuralnet::compute(nn_ablone,testData[, 1:10])
predictions_test <- max.col(compute_test$net.result)
original_values <- max.col(testData[,c(15:30)])
result.abl[5,"test.error"]<-mean(original_values!=predictions_test)*20


}










###################finished with ablone dataset######################
```



```{r Exploratory & formal analysis car , echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
skim(car)




tab2 <- table(car$class)
tab2<- as.data.frame(tab2)
colnames(tab2) <- c("class", "number")

ggplot(data = tab2, mapping = aes(x =class, y = number)) +
  geom_col()

 class.buying<- table(car$class,car$Buying)
 class.buying <- as.data.frame( class.buying)
 colnames(class.buying) <- c("class", "buying", "number")

 ggplot(data = class.buying, mapping = aes(x = buying, y = number, fill = class)) +
  geom_col() +
  labs(x = "buying", y = "class",
        title = "class distribution buying price wise") 

ggplot(data = class.buying, mapping = aes(x = buying, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "buying", y = "class",
        title = "class distribution buying price wise") 

ggplot(data = class.buying, mapping = aes(x = buying, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "buying", y = "class",
        title = "class distribution buying price wise") 

#second var maint
  class.maint<- table(car$class,car$maint)
 class.maint <- as.data.frame( class.maint)
 colnames(class.maint) <- c("class", "maint", "number")

 ggplot(data = class.maint, mapping = aes(x = maint, y = number, fill = class)) +
  geom_col() +
  labs(x = "maint", y = "class",
        title = "class distribution maintainence price wise") 

ggplot(data = class.maint, mapping = aes(x = maint, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "maint", y = "class",
        title = "class distribution maint price wise") 

ggplot(data = class.maint, mapping = aes(x = maint, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "maint", y = "class",
        title = "class distribution doors number wise") 

  #third variable doors
  class.doors<- table(car$class,car$doors)
 class.doors <- as.data.frame( class.doors)
 colnames(class.doors) <- c("class", "doors", "number")

 ggplot(data = class.doors, mapping = aes(x = doors, y = number, fill = class)) +
  geom_col() +
  labs(x = "doors", y = "class",
        title = "class distribution doors number wise") 

ggplot(data = class.doors, mapping = aes(x = doors, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "doors", y = "class",
        title = "class distribution doors number wise") 

ggplot(data = class.doors, mapping = aes(x = doors, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "doors", y = "class",
        title = "class distribution doors number wise") 


#fourth variable persons
  class.persons<- table(car$class,car$persons)
 class.persons <- as.data.frame( class.persons)
 colnames(class.persons) <- c("class", "persons", "number")

 ggplot(data = class.persons, mapping = aes(x = persons, y = number, fill = class)) +
  geom_col() +
  labs(x = "persons", y = "class",
        title = "class distribution persons number wise") 

ggplot(data = class.persons, mapping = aes(x = persons, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "persons", y = "class",
        title = "class distribution persons number wise") 

ggplot(data = class.persons, mapping = aes(x = persons, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "persons", y = "class",
        title = "class distribution persons number wise") 
  
#5th variable  persons
  class.lug<- table(car$class,car$lug.boot)
 class.lug <- as.data.frame( class.lug)
 colnames(class.lug) <- c("class", "lug", "number")

 ggplot(data = class.lug, mapping = aes(x = lug, y = number, fill = class)) +
  geom_col() +
  labs(x = "lug", y = "class",
        title = "class distribution lug space wise") 

ggplot(data = class.lug, mapping = aes(x = lug, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "lug", y = "class",
        title = "class distribution lug space wise") 

ggplot(data = class.lug, mapping = aes(x = lug, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "lug", y = "class",
        title = "class distribution lug space wise") 
  
  #6th var safety
   class.safety<- table(car$class,car$safety)
 class.safety <- as.data.frame( class.safety)
 colnames(class.safety) <- c("class", "safety", "number")

 ggplot(data = class.safety, mapping = aes(x = safety, y = number, fill = class)) +
  geom_col() +
  labs(x = "safety", y = "class",
        title = "class distribution safety wise") 

ggplot(data = class.safety, mapping = aes(x = safety, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "safety", y = "class",
        title = "class distribution safety wise") 

ggplot(data = class.safety, mapping = aes(x = safety, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "safety", y = "class",
        title = "class distribution safety wise") 
  #start formal analysis now
  
  
  
  #dividing the data set into training and testing sub datasets
split <- c(0.5,0.55,0.6,0.65,0.7)
n <- dim(car)[1]
result.car<- data.frame(method = c("Simple Multinomial","Reduced Variable Multinomial", "RandomForest","Neural Network"), training.error = c(0),test.error = c(0))

for(alpha in split)
{

set.seed(1)
ind <- sample(c(1:n),alpha*n) # 60%-40% training and test split
car.train <- car[ ind,] 
car.test <- car[-ind,]
#applied multinomial
multi.car <- multinom( class ~ .,data = car.train,maxit = 1000)
result.car[1,"training.error"]<-mean(car.train$class!=predict(c1))*20
result.car[1,"test.error"]<-mean(car.test$class!=predict(c1,car.test))*20

#variable reduction
step_both_car <- stepAIC(c1, direction="both",trace = FALSE)
result.car[2,"training.error"]<-mean(car.train$class!=predict(step_both_car))
result.car[2,"test.error"]<-mean(car.test$class!=predict(step_both_car,car.test))
#apply randomforest
car.raf <- randomForest(class~., data = car.train, ntree = 200)
result.car[3,"training.error"]<-mean(car.train$class!=predict(car.raf))
result.car[3,"training.error"]<-mean(car.test$class!=predict(car.raf,car.test))

#apply  neural network
car_matrix <- model.matrix(~Buying+maint+doors+persons+lug.boot+safety, data=car.train)
car_matrix <- car_matrix[,-1]


f <- paste(colnames(car_matrix_final[,1:15]),collapse="+")
trainData <- cbind(class.ind(car.train$class),car_matrix)


#prepare test data
car_matrix1 <- model.matrix(~Buying+maint+doors+persons+lug.boot+safety, data=car.test)
car_matrix1 <- car_matrix1[,-1]
testData <- cbind(class.ind(car.test$class),car_matrix1)
set.seed(81)
nn_car1 <- neuralnet( acc+good+unacc+vgood~.,data = trainData ,hidden = c(3,5,3) ,linear.output=FALSE,err.fct='ce')

original_values <- max.col(trainData[,c(1:4)])
predictions <- max.col(nn_car1$net.result[[1]])
result.car[4,"training.error"]<-mean(original_values!=predictions)

compute_test <- neuralnet::compute(nn_car1,testData[, 5:19])
predictions_test <- max.col(compute_test$net.result)
original_values <- max.col(testData[,c(1:4)])
result.car[4,"test.error"]<-mean(original_values!=predictions_test)



}



table(car.test$class,predict(car.raf,car.test))

```

```{r Exploratory & formal analysis nursery, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
skim(nursery)




tab2 <- table(nursery$class)
tab2<- as.data.frame(tab2)
colnames(tab2) <- c("class", "number")

ggplot(data = tab2, mapping = aes(x =class, y = number)) +
  geom_col()

 class.parents<- table(nursery$class,nursery$parents)
 class.parents <- as.data.frame( class.parents)
 colnames(class.parents) <- c("class", "parents", "number")

 ggplot(data = class.parents, mapping = aes(x = parents, y = number, fill = class)) +
  geom_col() +
  labs(x = "parents", y = "class",
        title = "class distribution parents wise") 

ggplot(data = class.parents, mapping = aes(x = parents, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "parents", y = "class",
        title = "class distribution parents wise") 

ggplot(data = class.parents, mapping = aes(x = parents, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "parents", y = "class",
        title = "class distribution parents wise") 

#second var has_nurs
  class.nurs<- table(nursery$class,nursery$has_nurs)
 class.nurs <- as.data.frame( class.nurs)
 colnames(class.nurs) <- c("class", "has_nurs", "number")

 ggplot(data = class.nurs, mapping = aes(x = has_nurs, y = number, fill = class)) +
  geom_col() +
  labs(x = "has_nurs", y = "class",
        title = "class distribution has_nurs wise") 

ggplot(data = class.nurs, mapping = aes(x = has_nurs, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "has_nurs", y = "class",
        title = "class distribution has_nurs wise") 

ggplot(data = class.nurs, mapping = aes(x = has_nurs, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "has_nurs", y = "class",
        title = "class distribution parents wise") 

  #third variable form
 class.form<- table(nursery$class,nursery$form)
 class.form <- as.data.frame( class.form)
 colnames(class.form) <- c("class", "form", "number")

 ggplot(data = class.form, mapping = aes(x = form, y = number, fill = class)) +
  geom_col() +
  labs(x = "form", y = "class",
        title = "class distribution form wise") 

ggplot(data = class.form, mapping = aes(x = form, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "form", y = "class",
        title = "class distribution form wise") 

ggplot(data = class.form, mapping = aes(x = form, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "form", y = "class",
        title = "class distribution form wise") 

#fourth variable children
   class.children<- table(nursery$class,nursery$children)
 class.children <- as.data.frame( class.children)
 colnames(class.children) <- c("class", "children", "number")

 ggplot(data = class.children, mapping = aes(x = children, y = number, fill = class)) +
  geom_col() +
  labs(x = "children", y = "class",
        title = "class distribution children wise") 

ggplot(data = class.children, mapping = aes(x = children, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "children", y = "class",
        title = "class distribution children wise") 

ggplot(data = class.children, mapping = aes(x = children, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "children", y = "class",
        title = "class distribution children wise") 
#5th variable  housing
    class.housing<- table(nursery$class,nursery$housing)
 class.housing <- as.data.frame( class.housing)
 colnames(class.housing) <- c("class", "housing", "number")

 ggplot(data = class.housing, mapping = aes(x = housing, y = number, fill = class)) +
  geom_col() +
  labs(x = "housing", y = "class",
        title = "class distribution housing wise") 

ggplot(data = class.housing, mapping = aes(x = housing, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "housing", y = "class",
        title = "class distribution housing wise") 

ggplot(data = class.housing, mapping = aes(x = housing, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "housing", y = "class",
        title = "class distribution housing wise") 
  
  #6th var finance
  class.finance<- table(nursery$class,nursery$finance)
 class.finance <- as.data.frame( class.finance)
 colnames(class.finance) <- c("class", "finance", "number")

 ggplot(data = class.finance, mapping = aes(x = finance, y = number, fill = class)) +
  geom_col() +
  labs(x = "finance", y = "class",
        title = "class distribution finance wise") 

ggplot(data = class.finance, mapping = aes(x = finance, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "finance", y = "class",
        title = "class distribution finace wise") 

ggplot(data = class.finance, mapping = aes(x = finance, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "finance", y = "class",
        title = "class distribution finance wise") 
  
#7th variable social
  class.social<- table(nursery$class,nursery$social)
 class.social <- as.data.frame( class.social)
 colnames(class.social) <- c("class", "social", "number")

 ggplot(data = class.social, mapping = aes(x = social, y = number, fill = class)) +
  geom_col() +
  labs(x = "social", y = "class",
        title = "class distribution social wise") 

ggplot(data = class.social, mapping = aes(x = social, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "social", y = "class",
        title = "class distribution social wise") 

ggplot(data = class.social, mapping = aes(x = social, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "social", y = "class",
        title = "class distribution social wise") 
  
  #8th variable health
  class.health<- table(nursery$class,nursery$health)
 class.health <- as.data.frame( class.health)
 colnames(class.health) <- c("class", "health", "number")

 ggplot(data = class.health, mapping = aes(x = health, y = number, fill = class)) +
  geom_col() +
  labs(x = "health", y = "class",
        title = "class distribution social wise") 

ggplot(data = class.health, mapping = aes(x = health, y = number, fill = class)) +
  geom_col(position = "dodge") +
  labs(x = "health", y = "class",
        title = "class distribution social wise") 

ggplot(data = class.health, mapping = aes(x = health, y = number, fill = class)) +
  geom_col() +
  facet_wrap(~class,ncol = 1)
  labs(x = "health", y = "class",
        title = "class distribution health wise")  
  
  #start formal analysis now
  #remove outliers
  mean(nursery$class=="recommend")
  nursery<- subset(nursery, class!="recommend")
  
  #dividing the data set into training and testing sub datasets

   #dividing the data set into training and testing sub datasets
split <- c(0.5,0.55,0.6,0.65,0.7)
n <- dim(nursery)[1]
result.nur<- data.frame(method = c("Simple Multinomial","Reduced Variable Multinomial", "RandomForest","Neural Network"), training.error = c(0),test.error = c(0))

for(alpha in split)
{

set.seed(1)

ind <- sample(c(1:n),alpha*n) 
nursery.train <- nursery[ ind,] 
nursery.test <- nursery[-ind,]
nursery.mul <- multinom( class ~ .,data = nursery.train,maxit = 1000)

result.nur[1,"training.error"]<-mean(as.character(nursery.train$class)!=as.character(predict(nursery.mul)))*20
result.nur[1,"test.error"]<-mean(as.character(nursery.test$class)!=as.character(predict(nursery.mul,nursery.test)))*20
#variable selection
step_both_nur <- stepAIC(nursery.mul, direction="both")
result.nur[2,"training.error"]<-mean(as.character(nursery.train$class)!=as.character(predict(step_both_nur)))*20
result.nur[2,"test.error"]<-mean(as.character(nursery.test$class)!=as.character(predict(step_both_nur,nursery.test)))*20

#apply randomforest
nursery.train <- droplevels(nursery.train )
nursery.raf <- randomForest(class~., data = nursery.train, ntree = 200)

result.nur[3,"training.error"]<-mean(as.character(nursery.train$class)!=as.character(predict(nursery.raf)))
result.nur[3,"test.error"]<-mean(as.character(nursery.test$class)!=as.character(predict(nursery.raf,nursery.test)))

#apply  neural network
nursery_matrix <- model.matrix(~parents+has_nurs+form+children+housing+finance+social+health, data=nursery.train)
nursery_matrix <- nursery_matrix[,-1]



trainData <- cbind(class.ind(nursery.train$class),nursery_matrix)
head(trainData)

#prepare test data
nursery_matrix1 <- model.matrix(~parents+has_nurs+form+children+housing+finance+social+health, data=nursery.test)
nursery_matrix1 <- nursery_matrix1[,-1]
testData <- cbind(class.ind(nursery.test$class),nursery_matrix1)


#best 55***, 54,53***,
set.seed(81)
nn_nursery <- neuralnet( not_recom+priority+spec_prior+very_recom~.,data = trainData ,hidden = c(5,3) ,linear.output=FALSE,err.fct='ce')

original_values <- max.col(trainData[,c(1:4)])
predictions <- max.col(nn_nursery$net.result[[1]])
result.nur[4,"training.error"]<-mean(original_values!=predictions)

compute_test <- neuralnet::compute(nn_nursery,testData[,6:24])
predictions_test <- max.col(compute_test$net.result)
original_values <- max.col(testData[,c(1,2,4,5)])
result.nur[4,"test.error"]<-mean(original_values!=predictions_test)



}



  
```

```{r Exploratory & formal analysis contra, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

contra$w.education <-as.factor(contra$w.education)
contra$h.education <-as.factor(contra$h.education)
contra$religion <-as.factor(contra$religion)
contra$working <-as.factor(contra$working)
contra$occupation<- as.factor(contra$occupation)
contra$standard<- as.factor(contra$standard)
contra$media <-as.factor(contra$media)
contra$contraceptive<- as.factor(contra$contraceptive)

skim(contra)

tab2 <- table(contra$contraceptive)
tab2<- as.data.frame(tab2)
colnames(tab2) <- c("contraceptive", "number")

ggplot(data = tab2, mapping = aes(x =contraceptive, y = number)) +
  geom_col()

contra %>%
  ggplot(aes(x = contraceptive,y = age)) +
  geom_boxplot() +
  labs(x = "contraceptive", y = "wife age",title="Boxplot of contraceptive vs wife age")
  
contra %>%
  ggplot(aes(x = contraceptive,y = children)) +
  geom_boxplot() +
  labs(x = "contraceptive", y = "children",title="Boxplot of contraceptive vs number of children")
#first variable wife education
  contra.wife<- table(contra$contraceptive,contra$w.education)
 contra.wife <- as.data.frame( contra.wife)
 colnames(contra.wife) <- c("contra", "w.education", "number")

 ggplot(data = contra.wife, mapping = aes(x = w.education, y = number, fill =contra )) +
  geom_col() +
  labs(x = "wife education", y = "contraceptive",
        title = "contraceptive distribution wife education wise") 

ggplot(data = contra.wife, mapping = aes(x = w.education, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "wife education", y = "contraceptive",
        title = "contraceptive distribution wife education wise") 

ggplot(data = contra.wife, mapping = aes(x = w.education, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "wife education", y = "contraceptive",
        title = "contraceptive distribution wife education wise")  

#second variable husband education
  contra.husband<- table(contra$contraceptive,contra$h.education)
 contra.husband <- as.data.frame( contra.husband)
 colnames(contra.husband) <- c("contra", "h.education", "number")

 ggplot(data = contra.husband, mapping = aes(x = h.education, y = number, fill =contra )) +
  geom_col() +
  labs(x = "husband education", y = "contraceptive",
        title = "contraceptive distribution husband education wise") 

ggplot(data = contra.husband, mapping = aes(x = h.education, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "husband education", y = "contraceptive",
        title = "contraceptive distribution husband education wise") 

ggplot(data = contra.husband, mapping = aes(x = h.education, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "husband education", y = "contraceptive",
        title = "contraceptive distribution husband education wise")  


#third variable Wife's religion
  contra.religion<- table(contra$contraceptive,contra$religion)
 contra.religion <- as.data.frame( contra.religion)
 colnames(contra.religion) <- c("contra", "religion", "number")

 ggplot(data = contra.religion, mapping = aes(x = religion, y = number, fill =contra )) +
  geom_col() +
  labs(x = "religion", y = "contraceptive",
        title = "contraceptive distribution wife relision wise") 

ggplot(data = contra.religion, mapping = aes(x = religion, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "wife religion", y = "contraceptive",
        title = "contraceptive distribution wife religion wise") 

ggplot(data = contra.religion, mapping = aes(x =religion, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "religion", y = "contraceptive",
        title = "contraceptive distribution religion wise")  

#forth variable Wife's now working
  contra.work<- table(contra$contraceptive,contra$working)
 contra.work <- as.data.frame( contra.work)
 colnames(contra.work) <- c("contra", "work", "number")

 ggplot(data = contra.work, mapping = aes(x = work, y = number, fill =contra )) +
  geom_col() +
  labs(x = "work", y = "contraceptive",
        title = "contraceptive distribution wife working wise") 

ggplot(data = contra.work, mapping = aes(x = work, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "wife working", y = "contraceptive",
        title = "contraceptive distribution wife working wise") 

ggplot(data = contra.work, mapping = aes(x =work, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "work", y = "contraceptive",
        title = "contraceptive distribution wife working wise")  
  

#fifth variable husband ocupation
  contra.occupation<- table(contra$contraceptive,contra$occupation)
 contra.occupation <- as.data.frame( contra.occupation)
 colnames(contra.occupation) <- c("contra", "occupation", "number")

 ggplot(data = contra.occupation, mapping = aes(x = occupation, y = number, fill =contra )) +
  geom_col() +
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise") 

ggplot(data = contra.occupation, mapping = aes(x = occupation, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise") 

ggplot(data = contra.occupation, mapping = aes(x =occupation, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise")  
  
#fifth variable husband ocupation
  contra.occupation<- table(contra$contraceptive,contra$occupation)
 contra.occupation <- as.data.frame( contra.occupation)
 colnames(contra.occupation) <- c("contra", "occupation", "number")

 ggplot(data = contra.occupation, mapping = aes(x = occupation, y = number, fill =contra )) +
  geom_col() +
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise") 

ggplot(data = contra.occupation, mapping = aes(x = occupation, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise") 

ggplot(data = contra.occupation, mapping = aes(x =occupation, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise")  
  
#fifth variable husband ocupation
  contra.occupation<- table(contra$contraceptive,contra$occupation)
 contra.occupation <- as.data.frame( contra.occupation)
 colnames(contra.occupation) <- c("contra", "occupation", "number")

 ggplot(data = contra.occupation, mapping = aes(x = occupation, y = number, fill =contra )) +
  geom_col() +
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise") 

ggplot(data = contra.occupation, mapping = aes(x = occupation, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise") 

ggplot(data = contra.occupation, mapping = aes(x =occupation, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "occupation", y = "contraceptive",
        title = "contraceptive distribution husband occupation wise")  
  
#6th variable Standard-of-living index 
  contra.standard<- table(contra$contraceptive,contra$standard)
 contra.standard <- as.data.frame( contra.standard)
 colnames(contra.standard) <- c("contra", "standard", "number")

 ggplot(data = contra.standard, mapping = aes(x = standard, y = number, fill =contra )) +
  geom_col() +
  labs(x = "standard", y = "contraceptive",
        title = "contraceptive distribution living standard wise") 

ggplot(data = contra.standard, mapping = aes(x = standard, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "standard", y = "contraceptive",
        title = "contraceptive distribution living standard wise") 

ggplot(data = contra.standard, mapping = aes(x =standard, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "standard", y = "contraceptive",
        title = "contraceptive distribution standard wise")  
  

#7th variable Media exposure
  contra.media<- table(contra$contraceptive,contra$media)
 contra.media <- as.data.frame( contra.media)
 colnames(contra.media) <- c("contra", "media", "number")

 ggplot(data = contra.media, mapping = aes(x = media, y = number, fill =contra )) +
  geom_col() +
  labs(x = "media", y = "contraceptive",
        title = "contraceptive distribution media exposure wise") 

ggplot(data = contra.media, mapping = aes(x = media, y = number, fill = contra)) +
  geom_col(position = "dodge") +
  labs(x = "media", y = "contraceptive",
        title = "contraceptive distribution media exposure wise") 

ggplot(data = contra.media, mapping = aes(x =media, y = number, fill = contra)) +
  geom_col() +
  facet_wrap(~contra,ncol = 1)
  labs(x = "media", y = "contraceptive",
        title = "contraceptive distribution media exposure wise")  
  
#apply formal analysis
   #dividing the data set into training and testing sub datasets
split <- c(0.5,0.55,0.6,0.65,0.7)
n <- dim(contra)[1]
result.contra<- data.frame(method = c("Simple Multinomial","Reduced Variable Multinomial", "RandomForest","Neural Network"), training.error = c(0),test.error = c(0))
maxs <- apply(contra[,c("age","children")], 2, max)
mins <- apply(contra[,c("age","children")], 2, min)

for(alpha in split)
{

set.seed(1)
ind <- sample(c(1:n),alpha*n) # 60%-40% training and test split
contra.train <- contra[ ind,] 
contra.test <- contra[-ind,]

contra.mul <- multinom( contraceptive ~ .,data = contra.train,maxit = 1000)


result.contra[1,"training.error"]<-mean(as.character(contra.train$contraceptive)!=as.character(predict(contra.mul)))
result.contra[1,"test.error"]<-mean(as.character(contra.test$contraceptive)!=as.character(predict(contra.mul,contra.test)))

#variable selection
step_both_con <- stepAIC(contra.mul, direction="both")
result.contra[2,"training.error"]<-mean(as.character(contra.train$contraceptive)!=as.character(predict(step_both_con)))
result.contra[2,"test.error"]<-mean(as.character(contra.test$contraceptive)!=as.character(predict(step_both_con,contra.test)))

#apply randomforest
contra.train <- droplevels(contra.train )
contra.raf <- randomForest(contraceptive~., data = contra.train, ntree = 200)

result.contra[3,"training.error"]<-mean(as.character(contra.train$contraceptive)!=as.character(predict(contra.raf)))
result.contra[3,"test.error"]<-mean(as.character(contra.test$contraceptive)!=as.character(predict(contra.raf,contra.test)))

contra_matrix <- model.matrix(~w.education+h.education+religion+working+occupation+standard +media , data=contra.train)
contra_matrix <- contra_matrix[,-1]



trainData <- cbind(class.ind(contra.train$contraceptive),contra_matrix,contra.train$age,contra.train$children)
#scaling

trainData[,c(19,20)]<-scale(trainData[,19:20], center = mins, scale = maxs - mins)
#prepare test data
contra_matrix1 <- model.matrix(~w.education+h.education+religion+working+occupation+standard +media , data=contra.test)
contra_matrix1 <- contra_matrix1[,-1]
testData <- cbind(class.ind(contra.test$contraceptive),contra_matrix1,contra.test$age,contra.test$children)

#scaling

testData[,19:20]<-scale(testData[,19:20], center = mins, scale = maxs - mins)

set.seed(81)
nn_contra <- neuralnet( `1`+`2`+`3`~.,data = trainData ,hidden = c(5) ,linear.output=FALSE,err.fct='ce')



original_values <- max.col(trainData[,c(1:3)])
predictions <- max.col(nn_contra$net.result[[1]])
result.contra[4,"training.error"]<-mean(original_values!=predictions)


compute_test <- neuralnet::compute(nn_contra,testData[,4:20])
predictions_test <- max.col(compute_test$net.result)
original_values <- max.col(testData[,c(1,2,3)])
result.contra[4,"test.error"]<-mean(original_values!=predictions_test)




}



contra.raf$confusion %>%
  kable(caption = ' Confusion matrix for contraceptive data')%>%
  kable_styling(latex_options="hold_position")
#apply  neural network





#best 6,4,5




```